name: Ansible Lint
description: Run Ansible Lint
inputs:
  path:
    required: false
    default: "."
runs:
  using: docker
  image: 'Dockerfile'
  entrypoint: yamllint 
  args:
    - ${{ inputs.path }}
